import Head from "next/head";
import Image from "next/image";
import Header from "../components/header";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Demo Lazurde Storefront</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <Image
          src={
            "https://cdn.lazurde.com/media/wysiwyg/home-slides/INSTYLE_NEW_COLLECTION_WEB_BANNERS_DECEMBER.jpg"
          }
          layout="fill"
        />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
